// Generates firestore.rules from src/data/schedule.json so pick-locking is
// enforced SERVER-side: a group pick can only change before that match's
// kickoff, and knockout picks only before the first Round-of-32 kickoff.
// Re-run after regenerating the schedule, then paste into the Firebase
// console (Firestore -> Rules) and publish.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const schedule = JSON.parse(readFileSync(join(ROOT, 'src/data/schedule.json'), 'utf8'));

const group = schedule.filter((m) => m.stage === 'group');
const koLock = Math.min(
  ...schedule.filter((m) => m.stage === 'r32').map((m) => Date.parse(m.dateUtc))
);

// One helper per 6 matches keeps rule expressions shallow enough.
const chunks = [];
for (let i = 0; i < group.length; i += 6) chunks.push(group.slice(i, i + 6));

const helpers = chunks
  .map((chunk, ci) => {
    const conds = chunk
      .map(
        (m) =>
          `(!d.hasAny(['${m.num}']) || request.time.toMillis() < ${Date.parse(m.dateUtc)})`
      )
      .join('\n        && ');
    return `    function grp${ci}(d) {\n      return ${conds};\n    }`;
  })
  .join('\n');

const allCall = chunks.map((_, ci) => `grp${ci}(d)`).join(' && ');

const rules = `rules_version = '2';

// GENERATED by scripts/gen-rules.mjs — do not edit by hand.
// Locks every group pick at its match kickoff and all knockout picks at the
// first Round-of-32 kickoff (${new Date(koLock).toISOString()}).

service cloud.firestore {
  match /databases/{database}/documents {

${helpers}

    function groupKeysUnlocked(d) {
      return ${allCall};
    }

    function knockoutUnlocked(d) {
      return d.size() == 0 || request.time.toMillis() < ${koLock};
    }

    function picksShapeOk() {
      return request.resource.data.keys().hasOnly(['group', 'knockout', 'updatedAt'])
        && request.resource.data.get('group', {}) is map
        && request.resource.data.get('knockout', {}) is map;
    }

    match /users/{uid} {
      allow read: if request.auth != null;
      allow create, update: if request.auth != null
        && request.auth.uid == uid
        && request.resource.data.displayName is string
        && request.resource.data.displayName.size() > 0
        && request.resource.data.displayName.size() <= 40;
    }

    match /picks/{uid} {
      allow read: if request.auth != null;
      allow create: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupKeysUnlocked(request.resource.data.get('group', {}).diff({}).affectedKeys())
        && knockoutUnlocked(request.resource.data.get('knockout', {}).diff({}).affectedKeys());
      allow update: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupKeysUnlocked(request.resource.data.get('group', {})
             .diff(resource.data.get('group', {})).affectedKeys())
        && knockoutUnlocked(request.resource.data.get('knockout', {})
             .diff(resource.data.get('knockout', {})).affectedKeys());
    }
  }
}
`;

writeFileSync(join(ROOT, 'firestore.rules'), rules);
console.log(`wrote firestore.rules (${group.length} group locks, knockout lock ${new Date(koLock).toISOString()})`);
