// Generates firestore.rules from src/data/schedule.json so pick-locking is
// enforced SERVER-side: each group's finishing order can only change before
// that group's first kickoff, third-place picks before the last group's first
// kickoff, and knockout picks before the first Round-of-32 kickoff.
// Re-run after regenerating the schedule, then paste into the Firebase
// console (Firestore -> Rules) and publish.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const schedule = JSON.parse(readFileSync(join(ROOT, 'src/data/schedule.json'), 'utf8'));

// first kickoff per group
const groupLocks = {};
for (const m of schedule) {
  if (m.stage !== 'group') continue;
  const t = Date.parse(m.dateUtc);
  if (!(m.group in groupLocks) || t < groupLocks[m.group]) groupLocks[m.group] = t;
}
const thirdsLock = Math.max(...Object.values(groupLocks));
const koLock = Math.min(
  ...schedule.filter((m) => m.stage === 'r32').map((m) => Date.parse(m.dateUtc))
);

const groupConds = Object.keys(groupLocks)
  .sort()
  .map((g) => `(!d.hasAny(['${g}']) || request.time.toMillis() < ${groupLocks[g]})`)
  .join('\n        && ');

const rules = `rules_version = '2';

// GENERATED by scripts/gen-rules.mjs — do not edit by hand.
// Each group's order locks at that group's first kickoff; third-place picks
// lock at the last group's first kickoff (${new Date(thirdsLock).toISOString()});
// knockout picks lock at the first Round-of-32 kickoff (${new Date(koLock).toISOString()}).

service cloud.firestore {
  match /databases/{database}/documents {

    function picksShapeOk() {
      return request.resource.data.keys().hasOnly(['groupOrder', 'thirds', 'knockout', 'updatedAt'])
        && request.resource.data.get('groupOrder', {}) is map
        && request.resource.data.get('thirds', []) is list
        && request.resource.data.get('thirds', []).size() <= 8
        && request.resource.data.get('knockout', {}) is map;
    }

    // d = the set of group letters whose order changed in this write.
    function groupKeysUnlocked(d) {
      return ${groupConds};
    }

    function thirdsOk(prevThirds) {
      return request.resource.data.get('thirds', []) == prevThirds
        || request.time.toMillis() < ${thirdsLock};
    }

    function knockoutOk(prevKnockout) {
      return request.resource.data.get('knockout', {}) == prevKnockout
        || request.time.toMillis() < ${koLock};
    }

    match /users/{uid} {
      allow read: if request.auth != null;
      allow create, update: if request.auth != null
        && request.auth.uid == uid
        && request.resource.data.displayName is string
        && request.resource.data.displayName.size() > 0
        && request.resource.data.displayName.size() <= 40;
    }

    match /picks/{uid} {
      allow read: if request.auth != null;
      allow create: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupKeysUnlocked(request.resource.data.get('groupOrder', {}).diff({}).affectedKeys())
        && thirdsOk([])
        && knockoutOk({});
      allow update: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupKeysUnlocked(request.resource.data.get('groupOrder', {})
             .diff(resource.data.get('groupOrder', {})).affectedKeys())
        && thirdsOk(resource.data.get('thirds', []))
        && knockoutOk(resource.data.get('knockout', {}));
    }
  }
}
`;

writeFileSync(join(ROOT, 'firestore.rules'), rules);
console.log(
  `wrote firestore.rules (12 group locks ${new Date(Math.min(...Object.values(groupLocks))).toISOString()}..${new Date(thirdsLock).toISOString()}, knockout lock ${new Date(koLock).toISOString()})`
);
