// Generates firestore.rules from src/data/schedule.json so pick-locking is
// enforced SERVER-side: group finishing orders and third-place picks can only
// change before the tournament's first kickoff, and knockout picks only
// before the first Round-of-32 kickoff.
// Re-run after regenerating the schedule, then paste into the Firebase
// console (Firestore -> Rules) and publish.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const schedule = JSON.parse(readFileSync(join(ROOT, 'src/data/schedule.json'), 'utf8'));

const groupLock = Math.min(
  ...schedule.filter((m) => m.stage === 'group').map((m) => Date.parse(m.dateUtc))
);
const koLock = Math.min(
  ...schedule.filter((m) => m.stage === 'r32').map((m) => Date.parse(m.dateUtc))
);

const rules = `rules_version = '2';

// GENERATED by scripts/gen-rules.mjs — do not edit by hand.
// Group orders + third-place picks lock at the opening kickoff
// (${new Date(groupLock).toISOString()}); knockout picks lock at the
// first Round-of-32 kickoff (${new Date(koLock).toISOString()}).

service cloud.firestore {
  match /databases/{database}/documents {

    function picksShapeOk() {
      return request.resource.data.keys().hasOnly(['groupOrder', 'thirds', 'knockout', 'updatedAt'])
        && request.resource.data.get('groupOrder', {}) is map
        && request.resource.data.get('thirds', []) is list
        && request.resource.data.get('thirds', []).size() <= 8
        && request.resource.data.get('knockout', {}) is map;
    }

    // Each section may only differ from what's stored before its lock time.
    function groupStageOk(prevOrder, prevThirds) {
      return (request.resource.data.get('groupOrder', {}) == prevOrder
          && request.resource.data.get('thirds', []) == prevThirds)
        || request.time.toMillis() < ${groupLock};
    }

    function knockoutOk(prevKnockout) {
      return request.resource.data.get('knockout', {}) == prevKnockout
        || request.time.toMillis() < ${koLock};
    }

    match /users/{uid} {
      allow read: if request.auth != null;
      allow create, update: if request.auth != null
        && request.auth.uid == uid
        && request.resource.data.displayName is string
        && request.resource.data.displayName.size() > 0
        && request.resource.data.displayName.size() <= 40;
    }

    match /picks/{uid} {
      allow read: if request.auth != null;
      allow create: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupStageOk({}, [])
        && knockoutOk({});
      allow update: if request.auth != null
        && request.auth.uid == uid
        && picksShapeOk()
        && groupStageOk(resource.data.get('groupOrder', {}), resource.data.get('thirds', []))
        && knockoutOk(resource.data.get('knockout', {}));
    }
  }
}
`;

writeFileSync(join(ROOT, 'firestore.rules'), rules);
console.log(
  `wrote firestore.rules (group lock ${new Date(groupLock).toISOString()}, knockout lock ${new Date(koLock).toISOString()})`
);
